### ISSUE TITLE
Videos with "strange" characters freeze the download

### ISSUE THREAD

**Issue by epeat96** [UnusAnnusArchived/TUAA-Downloader-React#1]
Episodes that cause trouble:
Season 0: episode 8 (verfified)
Season 1: episode 235, episode 7 (suspected)

The issue may be due to windows not allowing the "|" (vertical bar, pipe) character in a file name.
I suggest filtering out that character by replacing it with something else like whitespace or maybe "-" (hypen, minus sign)

**Comment by epeat96** [comment]
Some characters that cause the issue:
? |  /

**Comment by EverlyScott** [comment]
Committed a fix but people say it still gets stuck on s01.e038

**Comment by epeat96** [comment]
I am not an expert on regex and didnt even clone the repo to test this but i asked chatgpt for explanation on the regex used to filter out the problematic characters and it explained the following:

_"In JavaScript, fileName.replace(/[^A-Za-z0-9._\-\40]/, '_') replaces the first non-alphanumeric character (including anything other than letters, numbers, periods, underscores, hyphens, or spaces) in fileName with an underscore (_). To replace every such character in fileName, use the global flag g in the regex: /[^A-Za-z0-9._\-\40]/g. This modification ensures all non-matching characters are replaced, not just the first occurrence."_

As i said i dont know much about regex but the /g flag is commonly used in tools like sed and vim for global replacement, might also apply to JavaScript regex. In sed and vim, it replaces all occurrences in the text, not just the first. This concept could logically extend to JavaScript regex as well.

**Comment by epeat96** [comment]
Well now i actually took  the time to clone the repo and test this and it seems like the /g flag is the fix

**Comment by EverlyScott** [comment]
Could you add a pull request with the fix and ill be able to mess with it in a couple hours

**Comment by epeat96** [comment]
Done
